/// <reference types="@cloudflare/workers-types" />

// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
// @ts-expect-error Generated OpenNext output is not present before the build.
import { default as nextHandler } from "./.open-next/worker.js";

interface Env {
  APP_ORIGIN?: string;
  CRON_SECRET?: string;
}

async function scheduled(
  event: ScheduledController,
  env: Env,
): Promise<void> {
  const origin = env.APP_ORIGIN?.replace(/\/+$/, "");
  if (!origin || !env.CRON_SECRET) {
    console.error(
      "[cron] APP_ORIGIN or CRON_SECRET missing — skipping daily sweep.",
    );
    return;
  }

  const path =
    event.cron === "*/5 * * * *"
      ? "/api/cron/commerce-maintenance"
      : "/api/cron/daily";
  try {
    const response = await fetch(`${origin}${path}`, {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    if (!response.ok) {
      console.error(`[cron] ${path} returned ${response.status}`);
    }
  } catch (error) {
    console.error("[cron] daily sweep failed:", error);
  }
}

export default {
  fetch: nextHandler.fetch,
  scheduled,
} satisfies ExportedHandler<Env>;
